[package]
name = "node-e2e-tests"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true


[dependencies]
reth.workspace = true
reth-node-core.workspace = true
reth-primitives.workspace = true
reth-node-ethereum.workspace = true
reth-tracing.workspace = true

futures-util.workspace = true
eyre.workspace = true
tokio.workspace = true
serde_json.workspace = true
rand.workspace = true
secp256k1.workspace = true
alloy-signer.workspace = true
alloy-signer-wallet = { workspace = true, features = ["mnemonic"] }
alloy-rpc-types.workspace = true
alloy-network.workspace = true
alloy-consensus.workspace = true
